# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddOrderwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 290, 121, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 240, 121, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(510, 480, 261, 26))
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 255, 20);\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.labelTitlWindow = QtWidgets.QLabel(self.centralwidget)
        self.labelTitlWindow.setEnabled(False)
        self.labelTitlWindow.setGeometry(QtCore.QRect(190, 20, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.labelTitlWindow.setFont(font)
        self.labelTitlWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTitlWindow.setObjectName("labelTitlWindow")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 140, 321, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 190, 321, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 240, 121, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 240, 121, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(400, 240, 121, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(530, 240, 121, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(660, 240, 121, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 290, 121, 41))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(400, 290, 121, 41))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(270, 290, 121, 41))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(660, 290, 121, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(530, 290, 121, 41))
        self.lineEdit_14.setObjectName("lineEdit_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Введите напиток"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.pushButton_8.setText(_translate("MainWindow", "Добавить заказ"))
        self.labelTitlWindow.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#290808;\">Панель создание заказа</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введите место(стол)"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Введите количество гостей"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "Введите блюда"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Введите напиток"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Введите напиток"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "Введите напиток"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "Введите напиток"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "Введите напиток"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
